Style/Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin//**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  NewCops: enable