---
version: 2.1

references:
  bundle_cache_key: &bundle_cache_key
    rails_app-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

  yarn_cache_key: &yarn_cache_key
    yarn-cache-v1-{{ checksum "yarn.lock" }}

executors:
  default:
    working_directory: ~/rails_app
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: rails_app
          RAILS_ENV: test
          NODE_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: rails_app
          POSTGRES_DB: rails_app_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust

commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          name: Restoring bundle cache
          keys:
            - *bundle_cache_key
      - restore_cache:
          name: Restoring yarn cache
          keys:
            - *yarn_cache_key
      - configure_bundler
      - run:
          name: Installing bundle
          command: bundle install
      - run:
          name: Waiting for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - run:
          name: Setting up database
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: Installing Yarn Packages
          command: yarn install --cache-folder ~/.cache/yarn
      - run:
          name: Compiling webpacker
          command: bundle exec rake webpacker:compile
      - save_cache:
          name: Saving Bundle Cache
          key: *bundle_cache_key
          paths:
            - vendor/bundle
      - save_cache:
          name: Saving Yarn Package Cache
          key: *yarn_cache_key
          paths:
            - ./node_modules
      - run:
          name: Running rails Tests
          command: bundle exec rake
      - run:
          name: Running Rubocop lints
          command: bundle exec rubocop
workflows:
  version: 2
  integration:
    jobs:
      - build
