default: &default
  adapter: 'postgresql'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_awesome_app_development
  username: postgres
  password: Sophie@1993
test:
  <<: *default
  database: my_awesome_app_test
  username: postgres
  password: Sophie@1993

production:
  <<: *default
  database: my_awesome_app_production