default: &default
  adapter: 'postgresql'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_awesome_app_development


test:
  <<: *default
  database: my_awesome_app_test


  <<: *default
  database: my_awesome_app_production